clear;close all;
ID_Model_ITRI;
dataname = "G03circle";
number = xlsread(dataname+".xlsx");
% col 01: index
% col 02: X_pulse (rk)
% col 03: Z_pulse (rk)
% col 04: X_encoder
% col 05: Z_encoder
% col 06: X_Vcmd: ITRI velocity command
% col 07: Z_Vcmd: ITRI velocity command
% col 08: X_Vcmd: NCTU velocity command
% col 09: Z_Vcmd: NCTU velocity command
% col 10: X_actual torque
% col 11: Z_actual torque
finalindex = length(number);

Ts = 0.001;
X_rk_real = number(1:finalindex,2);
X_yk_real = number(1:finalindex,4);
X_uk = number(1:finalindex,8);

X_rk = X_rk_real-X_rk_real(1);
X_yk = X_yk_real-X_rk_real(1);
X_Vin = X_uk;
X_Vout = (X_yk - [ X_yk(1); X_yk(1:end-1)])/Ts;

Z_rk_real = number(1:finalindex,3);
Z_yk_real = number(1:finalindex,5);
Z_uk = number(1:finalindex,9);

Z_rk = Z_rk_real-Z_rk_real(1);
Z_yk = Z_yk_real-Z_rk_real(1);
Z_Vin = Z_uk;
Z_Vout =( Z_yk_real - [ Z_yk_real(1); Z_yk_real(1:end-1)])/Ts;

rawdata = struct('dataname',dataname+" raw",...  
                 'X_uk',X_uk,...
                 'X_Vin',X_Vin,...
                 'X_Vout',X_Vout,...  
                 'Z_uk',Z_uk,...
                 'Z_Vin',Z_Vin,...
                 'Z_Vout',Z_Vout...                 
                );
shiftdata = struct('dataname',dataname+" shift",...  
                   'X_rk',X_rk,...
                   'X_yk',X_yk,...
                   'Z_rk',Z_rk,...
                   'Z_yk',Z_yk,...   
                   'Ts',Ts...
                  );
mmdata = struct('dataname',dataname+" mm",...  
                'X_rk',X_rk*plantX_ITRI.count2round*plantX_ITRI.round2mm,...
                'X_yk',X_yk*plantX_ITRI.count2round*plantX_ITRI.round2mm,...
                'Z_rk',Z_rk*plantZ_ITRI.count2round*plantZ_ITRI.round2mm,...
                'Z_yk',Z_yk*plantZ_ITRI.count2round*plantZ_ITRI.round2mm,...       
                'Ts',Ts...                
               );
           
% figure();plot([Z_rk,Z_yk]*plantZ_ITRI.count2round*plantZ_ITRI.round2mm);
% rms(Z_rk-Z_yk)
